### ISSUE TITLE
[bug] tests expected to fail pass even if the expected message doesn't match the actual error message

### ISSUE THREAD

**Issue by beluamat29** [ngarbezza/testy#285]
## Describe the bug

When running a test that's expected to fail using `expectFailureOn()` the test passes even if the expected error message doesn't match the actual error message from the test run 

## To Reproduce

- Add a test you expect to fail, or modify one of the existing ones making the I18nMessage sent as argument in `expectFailureOn()` be any random string.
<img width="1123" alt="image" src="https://github.com/ngarbezza/testy/assets/9338235/1403ef90-f21c-4009-893c-b9d9fa2e984c">

- Run the test and verify that the test passes
<img width="792" alt="image" src="https://github.com/ngarbezza/testy/assets/9338235/ef72d322-735f-44dc-b079-39991673d009">

## Expected behavior

The message from the assertion failure should match the one expected in the test file. If they don't match the test should not pass

**Comment by ngarbezza** [comment]
I found the problem. For default equality assertions, we were relying on Node's `assert#deepStrictEqual` function. This functions compares objects by enumerating their properties. Properties must be enumerable.

When I introduced private fields as a "refactor", I broke the equality for these objects, because private properties are not enumerable, therefore the equality always returned `true` (no enumerable properties to compare).

I will work on the issue and release a new version with the fix.
